<a href="https://colab.research.google.com/github/kartik2627/linear_regression/blob/main/Linear_Algebra_Handson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing the numpy
import numpy as np

In [ ]:
# Defining Matrices
A = np.array([[1,2],[3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
B = np.array([[9,8], [7,6], [5,4]])
B

array([[9, 8],
       [7, 6],
       [5, 4]])

In [ ]:
len(A)

3

In [ ]:
(A[0])

array([1, 2])

In [ ]:
A[1][1]

4

Mathematical Operations
1. Addition
2. Subtraction
3. Scalar Multiplication

In [ ]:
# Addition of A and B
add_mat = np.array([[0,0],[0,0],[0,0]])

for i in range(len(A)):
  for j in range(len(A[0])):
    add_mat[i][j] = A[i][j] + B[i][j]

add_mat

array([[10, 10],
       [10, 10],
       [10, 10]])

In [ ]:
# Subtraction of A and B
sub_mat = np.array([[0,0],[0,0],[0,0]])

for i in range(len(A)):
  for j in range(len(A[0])):
    sub_mat[i][j] = A[i][j] - B[i][j]

sub_mat

array([[-8, -6],
       [-4, -2],
       [ 0,  2]])

In [ ]:
# Multiplication of A and scalar
mult_mat = np.array([[0,0],[0,0],[0,0]])
scalar = 5
for i in range(len(A)):
  for j in range(len(A[0])):
    mult_mat[i][j] = A[i][j] * scalar

mult_mat

array([[ 5, 10],
       [15, 20],
       [25, 30]])

In [ ]:
# Multplication of A with scalar easy way
mul_mat2 = A * scalar
mul_mat2

array([[ 5, 10],
       [15, 20],
       [25, 30]])